[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_2048 = "BRQU3JmG9KwyzgpyTrmvB2BpqonForuoj8tio9SydXrR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/xingyue/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
